

### Login de usuario
POST http://localhost:3000/usuarios/login
Content-Type: application/json

{
"email": "admin@correo.com",
  "password": "admin123"

}

### Listar usuarios (requiere token válido)
GET http://localhost:3000/usuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBjb3JyZW8uY29tIiwicm9sIjoiYWRtaW4iLCJpYXQiOjE3NTEwNzIzMzMsImV4cCI6MTc1MTA3NTkzM30.dBPCHZ510En3DFQ6e3T6w15VWT87SxlKZjjbwG3aX7A

### Crear usuario (sólo admin)
POST http://localhost:3000/usuarios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBjb3JyZW8uY29tIiwicm9sIjoiYWRtaW4iLCJpYXQiOjE3NTEwNjc3MzksImV4cCI6MTc1MTA3MTMzOX0.wZPdyuYVfCqVtJMw2C6rDEz-HEnjzIcxOflEFMHPoOo

{
  "nombre": "Operador prueba roles",
  "email": "operador1@mail.com",
  "password": "operador12345",
  "rol": "operador"
}

### Eliminar usuario (sólo admin)
DELETE http://localhost:3000/usuarios/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJvcGVyYWRvcjFAbWFpbC5jb20iLCJyb2wiOiJvcGVyYWRvciIsImlhdCI6MTc1MTA2ODE0MiwiZXhwIjoxNzUxMDcxNzQyfQ.8BY6Ik0F7SLS1FYIG-JNOZA5RJ4rh0SXkw8RbgbzI34
