

### Login y recibir cookie con token
POST http://localhost:3000/usuarios/login
Content-Type: application/json

{
  "email": "admin@correo.com",
  "password": "admin123"
}

### Acceder a ruta protegida con cookie (token en background)
GET http://localhost:3000/usuarios

### Logout - eliminar token
POST http://localhost:3000/usuarios/logout


### Listar usuarios (requiere token válido)
GET http://localhost:3000/usuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBjb3JyZW8uY29tIiwicm9sIjoiYWRtaW4iLCJpYXQiOjE3NTExMjQ1MjAsImV4cCI6MTc1MTEyODEyMH0.MsxuWq1wqyeinaasY2ZUsAHcYxqiMnhS1mZB_BfFSiQ

### Crear usuario (sólo admin)
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "nombre": "Operador prueba roles",
  "email": "operador1@mail.com",
  "password": "operador12345",
  "rol": "operador"
}

### Eliminar usuario (sólo admin)
DELETE http://localhost:3000/usuarios/5


### Crear vehículo
POST http://localhost:3000/vehiculos

Content-Type: application/json

{
  "patente": "YZ12",
  "marca": "Ford",
  "modelo": "Fiesta"
}

### Listar vehículos
GET http://localhost:3000/vehiculos

### Eliminar vehículo
DELETE http://localhost:3000/vehiculos/XYZ123
